version: "3.8"

services:
  url-shorter:
    build: ./
    command: ./wait-for-postgres.sh postgres_db ./url-shorter
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
      - redis_db
    environment:
      - POSTGRES_PASSWORD=qwerty
      - DB_TYPE=${DB_TYPE}
  postgres_db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
  redis_db:
    image: redis:latest
    ports:
      - 6379:6379
    